#!/usr/bin/env bash
READLINK=readlink
which greadlink && READLINK=greadlink

pluginpath="$(dirname "$($READLINK -f $0)")"

git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh

mkdir -p "$HOME/bin"
ln -svf "$pluginpath/bin/bump" "$HOME/bin/bump"
ln -svf "$pluginpath/bin/pj" "$HOME/bin/pj"
ln -svf "$pluginpath/bin/crt" "$HOME/bin/crt"
ln -svf "$pluginpath/bin/kubekill" "$HOME/bin/kubekill"
ln -svf "$pluginpath/bin/cf" "$HOME/bin/cf"
ln -svf "$pluginpath/bin/gtrain" "$HOME/bin/gtrain"
ln -svf "$pluginpath/zshrc" "$HOME/.zshrc"

